Add validation to start_clive.sh: * validate_no_pipeline - validates if there is no pipeline .

diff --git a/scripts/templates/start_clive.sh.template b/scripts/templates/start_clive.sh.template
--- a/scripts/templates/start_clive.sh.template
+++ b/scripts/templates/start_clive.sh.template
@@ -17,5 +17,13 @@ print_help() {
     echo
 }
 
+validate_no_pipeline() {
+    # validate no pipeline input for TUI mode
+    if [[ -n "${PIPELINE:-}" ]]; then
+        echo "Error: Pipeline cannot be passed to start_clive.sh script."
+        exit 3
+    fi
+}
+
 # Run the main function defined in the base script
 main "$@"
